### ISSUE TITLE
VS2015.1 breaks SyntaxExtensions hacks

### ISSUE THREAD

**Issue by Suchiman** [icsharpcode/RefactoringEssentials#124]
When you install Update 1 CTP and for example have following Code:
```csharp
if (false == true)
{
}
```
Set the cursor to `if` and press CTRL + . and you will get a crash from:
* ConvertExplicitToImplicitImplementationCodeRefactoringProvider
* ConvertImplicitToExplicitImplementationCodeRefactoringProvider
* NegateLogicalExpressionCodeRefactoringProvider
* InvertLogicalExpressionCodeRefactoringProvider

Stacktrace will always point to https://github.com/icsharpcode/RefactoringEssentials/blob/bb25d62f8610d863a3bc639dc1924585bf4373c9/RefactoringEssentials/Util/SyntaxExtensions.cs#L31
```
The type initializer for '"RefactoringEssentials.SyntaxExtensions' threw an exception.
 at RefactoringEssentials.SyntaxExtensions.GetExplicitInterfaceSpecifierSyntax(MemberDeclarationSyntax member)
 at RefactoringEssentials.CSharp.CodeRefactorings.ConvertExplicitToImplicitImplementationCodeRefactoringProvider.<ComputeRefactoringsAsync>d__0.MoveNext()
 --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.<GetRefactoringFromProviderAsync>d__8.MoveNext()
```

**Comment by Suchiman** [comment]
Fixed in #131
