### ISSUE TITLE
NullReferenceException in AnnotateLeaveEdgesWithTryFinallyBlocks in v3.2

### ISSUE THREAD

**Issue by duncansmart** [icsharpcode/RefactoringEssentials#174]
Dialog appears after opening solution, after which VS crashes/closes down:

    Unhandled exception:
    System.NullReferenceException
    Object reference not set to an instance of an object.
       at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.AnnotateLeaveEdgesWithTryFinallyBlocks()
       at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.BuildControlFlowGraph(StatementSyntax statement, SemanticModel typeResolveContext, Func`3 resolver, CancellationToken cancellationToken)
       at RefactoringEssentials.Util.Analysis.ControlFlowGraphBuilder.BuildControlFlowGraph(StatementSyntax statement, SemanticModel resolver, CancellationToken cancellationToken)
       at RefactoringEssentials.Util.Analysis.ReachabilityAnalysis.Create(StatementSyntax statement, SemanticModel resolver, RecursiveDetectorVisitor recursiveDetectorVisitor, CancellationToken cancellationToken)
       at RefactoringEssentials.CSharp.Diagnostics.FunctionNeverReturnsAnalyzer.GatherVisitor.VisitBody(String entityType, SyntaxToken markerToken, StatementSyntax body, ISymbol symbol, SyntaxKind accessorKind)
       at RefactoringEssentials.CSharp.Diagnostics.FunctionNeverReturnsAnalyzer.GatherVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at RefactoringEssentials.CSharp.Diagnostics.FunctionNeverReturnsAnalyzer.<>c__DisplayClass3_0.<<Initialize>b__1>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
       at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Any other info I can provide?

**Comment by mkrueger** [comment]
fixed
