### ISSUE TITLE
XmlDocAnalyzer causes unexpected exception which crashes Visual Studio

### ISSUE THREAD

**Issue by xprzemekw** [icsharpcode/RefactoringEssentials#180]
I am working with a large codebase, consisting of legacy files too. Since a few upgrades ago I constantly get the popup window with the following exception shown in it. After dismissing window with the Close button Visual Studio crashes. This appears few minutes after loading a solution file.

`Unhandled exception:
System.ArgumentOutOfRangeException
Specified argument was out of the range of valid values.
Parameter name: length
   at Microsoft.CodeAnalysis.Text.TextSpan..ctor(Int32 start, Int32 length)
   at RefactoringEssentials.CSharp.Diagnostics.XmlDocAnalyzer.GatherVisitor.AddXmlIssue(Int32 offset, Int32 length, String str)
   at RefactoringEssentials.CSharp.Diagnostics.XmlDocAnalyzer.GatherVisitor.CheckXmlDocForErrors(SyntaxNode node, ISymbol member)
   at RefactoringEssentials.CSharp.Diagnostics.XmlDocAnalyzer.GatherVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at RefactoringEssentials.CSharp.Diagnostics.XmlDocAnalyzer.GatherVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at RefactoringEssentials.CSharp.Diagnostics.XmlDocAnalyzer.GatherVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RefactoringEssentials.CSharp.Diagnostics.XmlDocAnalyzer.<>c__DisplayClass3_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by mkrueger** [comment]
Should be fixed. ty
