### ISSUE TITLE
NullReferenceException in StaticFieldOrAutoPropertyInGenericTypeAnalyzer in v3.2.279

### ISSUE THREAD

**Issue by duncansmart** [icsharpcode/RefactoringEssentials#181]
Dialog appears after opening solution, after which VS crashes/closes down:

    Unhandled exception:
    System.NullReferenceException
    Object reference not set to an instance of an object.
       at RefactoringEssentials.CSharp.Diagnostics.StaticFieldOrAutoPropertyInGenericTypeAnalyzer.GatherVisitor.VisitPropertyDeclaration(PropertyDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.PropertyDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
       at RefactoringEssentials.CSharp.Diagnostics.StaticFieldOrAutoPropertyInGenericTypeAnalyzer.GatherVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
       at RefactoringEssentials.CSharp.Diagnostics.StaticFieldOrAutoPropertyInGenericTypeAnalyzer.GatherVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
       at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
       at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
       at RefactoringEssentials.CSharp.Diagnostics.StaticFieldOrAutoPropertyInGenericTypeAnalyzer.<>c__DisplayClass3_0.<<Initialize>b__1>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
       at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Please let me know of there's anything else I can provide.

**Comment by mkrueger** [comment]
fixed
