### ISSUE TITLE
RedundantEmptyDefaultSwitchBranchAnalyzer crash

### ISSUE THREAD

**Issue by jakubsuchybio** [icsharpcode/RefactoringEssentials#196]
Hi,
I got this exception on the switch in this method: http://pastebin.com/VQmVWGVZ
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	RunUOPro		1	Active	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: RunUO
SyntaxTree: C:\dev\c#\manawydan\Scripts\Engines\Craft\Core\SelectCraftsManual.cs
SyntaxNode: switch( manual.RequiredRace ) { ... [SwitchStatementSyntax]@[46820..48287) (1417,3)-(1457,4)

System.NullReferenceException: Object reference not set to an instance of an object.
   at RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer.TryGetDiagnostic(SyntaxNodeAnalysisContext nodeContext, Diagnostic& diagnostic)
   at RefactoringEssentials.CSharp.Diagnostics.RedundantEmptyDefaultSwitchBranchAnalyzer.<>c.<Initialize>b__3_0(SyntaxNodeAnalysisContext nodeContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```
I am using latest 4.0.0 and VS2015 Update 2

**Comment by Rpinski** [comment]
Thank you for reporting!
