### ISSUE TITLE
Vsual Studio issue while opening .cshtml files

### ISSUE THREAD

**Issue by paul1956** [icsharpcode/RefactoringEssentials#212]
I install the latest source files but when I try to view any of the View cshtml files I get a VS popup and the log file has the following 2 errors

```
885	ERROR	System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.VisualStudio.Web.Editors.Razor.DesignTimeHost.RazorDnxCommandInvoker.InvokeNoProtocolAdded(String cmdLine) at Microsoft.VisualStudio.Web.Editors.Razor.DesignTimeHost.RazorDnxCommandInvoker.Initialize(ITextBuffer textBuffer, IDnxCommandInvoker dnxCommandInvoker) at Microsoft.VisualStudio.Web.Editors.Razor.DesignTimeHost.RazorDnxCommandInvoker.Create(ITextBuffer textBuffer) at Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator..ctor(ITextBuffer buffer, Version razorVersion, String physicalPath, String virtualPath) at Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.Create(ITextBuffer buffer, Version razorVersion, String physicalPath, String virtualPath) at Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGeneratorProvider.Microsoft.Html.Editor.Razor.IRazorCodeGeneratorProvider.CreateRazorCodeGenerator(ITextBuffer buffer, Version razorVersion, String physicalPath, String virtualPath) at Microsoft.Html.Editor.Razor.RazorCodeGeneratorFactory.CreateCodeGenerator(ITextBuffer buffer, Version razorVersion, String physicalPath, String virtualPath) at Microsoft.Html.Editor.ContentType.Handlers.RazorContentTypeHandler.Init(HtmlEditorTree editorTree) at Microsoft.Html.Editor.Document.HtmlEditorDocument..ctor(ITextBuffer textBuffer, IWebWorkspaceItem workspaceItem, Boolean disableContainedLanguages) at Microsoft.VisualStudio.Html.Package.Document.VsHtmlEditorDocument..ctor(IWebEditorInstance editorInstance, Boolean disableContainedLanguages) at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.HtmlDocumentFactoryProjectionsDisabled.CreateDocument(IWebEditorInstance editorInstance) at Microsoft.Html.Editor.EditorFactory.HtmlEditorInstance..ctor(IWebWorkspaceItem workspaceItem, ITextBuffer diskBuffer, IWebEditorDocumentFactory documentFactory) at Microsoft.Html.Editor.EditorFactory.HtmlEditorFactory.CreateEditorInstance(IWebWorkspaceItem workspaceItem, Object textBuffer, IWebEditorDocumentFactory documentFactory) at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.InitEditorInstance(ITextBuffer textBuffer) at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextBufferCreated(ITextBuffer textBuffer) at Microsoft.Web.Editor.Controller.TextViewConnectionListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers) at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass4_1.<.ctor>b__1() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
886	ERROR	System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.Close() at Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.OnClose(Object sender, EventArgs args) at System.EventHandler`1.Invoke(Object sender, TEventArgs e) at Microsoft.Html.Editor.Document.HtmlEditorDocument.Close() at Microsoft.VisualStudio.Html.Package.Document.VsHtmlEditorDocument.Close() at Microsoft.Html.Editor.Document.HtmlEditorDocument.Dispose(Boolean disposing) at Microsoft.Html.Editor.Commands.HtmlTextViewConnectionListener.OnTextBufferDisposing(ITextBuffer textBuffer) at Microsoft.VisualStudio.Html.Package.Commands.Html.VsHtmlTextViewConnectionListener.OnTextBufferDisposing(ITextBuffer textBuffer) at Microsoft.Web.Editor.Controller.TextViewConnectionListener.CheckForViewlessTextBuffers() at Microsoft.Web.Editor.Controller.TextViewConnectionListener.SubjectBuffersDisconnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers) at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass5_1.<Close>b__1() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

``
I am running VS 2015 Update 2

**Comment by Rpinski** [comment]
And you are sure that this only happens when RefactoringEssentials is enabled? In the stack trace I don't see anything connected to RefactoringEssentials.

**Comment by paul1956** [comment]
Sorry if I was unclear, RefactoringEssentials is not running, I am just trying to open one of its source files with Update 2. Maybe I need to post elsewhere, I thought someone else here may have seen the issue.

**Comment by paul1956** [comment]
I refreshed Visual Studio and the issue disappeared.

**Comment by vivekmj** [comment]
Opened the .cshtml in any other editor. Found a . after @ViewBag.Title   , and removed it.
