### ISSUE TITLE
NullReferenceException on ConvertConditionalTernaryToNullCoalescingAnalyzer

### ISSUE THREAD

**Issue by Gimly** [icsharpcode/RefactoringEssentials#264]
I'm getting the following exception in the output
```
SyntaxTree: C:\Sources\xxx.Domain\src\xxx.Domain\Statement.cs	
SyntaxNode: attachments == null ?  [ConditionalExpressionSyntax]@[663..687) (21,26)-(22,0)							

System.NullReferenceException: Object reference not set to an instance of an object.
   at RefactoringEssentials.CSharp.Diagnostics.ConvertConditionalTernaryToNullCoalescingAnalyzer.CanBeNull(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in C:\projects\refactoringessentials\RefactoringEssentials\CSharp\Diagnostics\Synced\Opportunities\ConvertConditionalTernaryToNullCoalescingAnalyzer.cs:line 113
   at RefactoringEssentials.CSharp.Diagnostics.ConvertConditionalTernaryToNullCoalescingAnalyzer.TryGetDiagnostic(SyntaxNodeAnalysisContext nodeContext, Diagnostic& diagnostic) in C:\projects\refactoringessentials\RefactoringEssentials\CSharp\Diagnostics\Synced\Opportunities\ConvertConditionalTernaryToNullCoalescingAnalyzer.cs:line 76
   at RefactoringEssentials.CSharp.Diagnostics.ConvertConditionalTernaryToNullCoalescingAnalyzer.<>c.<Initialize>b__3_0(SyntaxNodeAnalysisContext nodeContext) in C:\projects\refactoringessentials\RefactoringEssentials\CSharp\Diagnostics\Synced\Opportunities\ConvertConditionalTernaryToNullCoalescingAnalyzer.cs:line 37
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
```

It's linked to the following line of code:
`Attachments = attachments == null ? new List<Attachment>() : new List<Attachment>(attachments);`

This code cannot be translated into  a null coalescing operator as far as I know, it seems to make the analyzer fail for some reason.

**Comment by siegfriedpammer** [comment]
This was fixed by d8b513f2
