### ISSUE TITLE
CreateEventInvocatorCodeRefactoringProvider crashes (VS2017)

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/RefactoringEssentials#265]
class Program
	{
		public event EventHandler Test;

		static void Main(string[] args)
		{
		}
	}

RE crashes, when trying to create an event invocator (CreateEventInvocatorCodeRefactoringProvider):

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at RefactoringEssentials.ITypeSymbolExtensions.GenerateTypeSyntax(ITypeSymbol typeSymbol)
   at RefactoringEssentials.CSharp.CodeRefactorings.CreateEventInvocatorCodeRefactoringProvider.CreateMethodStub(Boolean isSealed,Boolean isStatic,String eventName,IMethodSymbol invokeMethod,Int32 parameterIndex)
   at RefactoringEssentials.CSharp.CodeRefactorings.CreateEventInvocatorCodeRefactoringProvider.CreateEventInvocator(String declaringTypeName,Boolean isSealed,Boolean isStatic,String eventName,IMethodSymbol invokeMethod,Boolean useExplictType)
   at RefactoringEssentials.CSharp.CodeRefactorings.CreateEventInvocatorCodeRefactoringProvider.CreateEventInvocator(Document document,ISymbol eventMember,Boolean useExplictType)
   at RefactoringEssentials.CSharp.CodeRefactorings.CreateEventInvocatorCodeRefactoringProvider.<>c__DisplayClass0_0.<ComputeRefactoringsAsync>b__0(CancellationToken t2)
   at RefactoringEssentials.InsertionAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass26_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by Rpinski** [comment]
In Roslyn 2.0 signature of `ITypeSymbolExtensions.GenerateTypeSyntax()` has changed.

**Comment by Rpinski** [comment]
We will need to separate the extension to a VS 2015 (= Roslyn 1.3) and a VS 2017 (= Roslyn 2.0) version, therefore we will fix this issue in the VS 2017 version later.
