### ISSUE TITLE
Argument Null Exception AD0001

### ISSUE THREAD

**Issue by immeraufdemhund** [icsharpcode/RefactoringEssentials#33]
System.ArgumentNullException: Value cannot be null.
Parameter name: node
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetConstantValueCore(SyntaxNode node, CancellationToken cancellationToken)
   at ICSharpCode.NRefactory6.CSharp.Diagnostics.ConstantConditionAnalyzer.Check(SyntaxNodeAnalysisContext nodeContext, ExpressionSyntax condition)
   at ICSharpCode.NRefactory6.CSharp.Diagnostics.ConstantConditionAnalyzer.<Initialize>b__3_4(SyntaxNodeAnalysisContext nodeContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass35_0`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by Rpinski** [comment]
Which version of Refactoring Essentials do you use? Because ``ICSharpCode.NRefactory6.CSharp.Diagnostics.ConstantConditionAnalyzer`` is the old namespace we used in NR6Pack. Since Refactoring Essentials the namespace is ``RefactoringEssentials.CSharp.Diagnostics.ConstantConditionAnalyzer``.

**Comment by immeraufdemhund** [comment]
I'm using 0.9.0 (according to NuGet is the newest non-prerelease) with VS2015 enterprise

**Comment by Rpinski** [comment]
Yes, NR6Pack has been renamed to "Refactoring Essentials" starting with release 1.0. For final Visual Studio 2015 you should install the latest **1.1**.
