### ISSUE TITLE
AddNullCheckCodeRefactoringProvider

### ISSUE THREAD

**Issue by CmdQ** [icsharpcode/RefactoringEssentials#333]
For me the yellow error bar keeps re-appearing and showing me the `AddNullCheckCodeRefactoringProvider` error, no matter how many times I clicked on “Don't show again”. After a couple of edits, it comes back.

> System.NullReferenceException : Object reference not set to an instance of an object.
>    at RefactoringEssentials.CSharp.AddNullCheckCodeRefactoringProvider.ConditionContainsNullCheck(ExpressionSyntax condition,ExpressionSyntax identifierToCheck)
>    at RefactoringEssentials.CSharp.AddNullCheckCodeRefactoringProvider.StatementWithConditionContainsNullCheck(SyntaxNode statement,ExpressionSyntax identifierToCheck)
>    at async RefactoringEssentials.CSharp.AddNullCheckCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)

**Comment by nick-morhun** [comment]
Hi, it would be very helpful to have a code example and where your cursor is when this happens.

**Comment by CmdQ** [comment]
Hi. I'm sorry but I don't have the state of that project anymore. In case I experience such behavior again, I'll document everything.
