### ISSUE TITLE
'ToAbstractVirtualNonVirtualConversionCodeRefactoringProvider' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by jojorne** [icsharpcode/RefactoringEssentials#335]
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.AnnotationExtensions.WithAdditionalAnnotations[TNode](TNode node,SyntaxAnnotation[] annotations)
   at RefactoringEssentials.CSharp.CodeRefactorings.ToAbstractVirtualNonVirtualConversionCodeRefactoringProvider.<>c__DisplayClass0_0.<ComputeRefactoringsAsync>b__8(CancellationToken t2)
   at RefactoringEssentials.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by nick-morhun** [comment]
Hi, I have fixed this in my fork.
