### ISSUE TITLE
System.NullReferenceException: RefactoringEssentials.CSharp.Diagnostics.LocalVariableHidesMemberAnalyzer

### ISSUE THREAD

**Issue by WizX20** [icsharpcode/RefactoringEssentials#339]
Visual Studio Community Edition 2017 v15.3.5
Refactoring Essentials 5.2.0.0

`Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.LocalVariableHidesMemberAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Bot		1	Active	Analyzer 'RefactoringEssentials.CSharp.Diagnostics.LocalVariableHidesMemberAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: MyBot.Project.MyBot.Bot
SyntaxTree: E:\Repos\SoBot\src\Project\MyBot.Bot\App_Start\UnityConfig.cs
SyntaxNode: var container = new UnityContainer ... [LocalDeclarationStatementSyntax]@[560..597) (19,12)-(19,49)`

[Full Exception.txt](https://github.com/icsharpcode/RefactoringEssentials/files/1366857/Full.Exception.txt)

[UnityConfig.cs.txt](https://github.com/icsharpcode/RefactoringEssentials/files/1366853/UnityConfig.cs.txt)

**Comment by n9** [comment]
Same issue, another stack trace.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RefactoringEssentials.SymbolExtensions.GetContainingTypeOrThis(ISymbol symbol)
   at RefactoringEssentials.CSharp.Diagnostics.LocalVariableHidesMemberAnalyzer.TryGetDiagnostic(SyntaxNodeAnalysisContext nodeContext, Diagnostic& diagnostic)
   at RefactoringEssentials.CSharp.Diagnostics.LocalVariableHidesMemberAnalyzer.<>c.<Initialize>b__3_0(SyntaxNodeAnalysisContext nodeContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by peteraritchie** [comment]
I get the same exception, let me know if there's something I can do to help find it.
