### ISSUE TITLE
RefactoringEssentials.CSharp.CodeRefactorings.IterateViaForeachAction

### ISSUE THREAD

**Issue by hack2root** [icsharpcode/RefactoringEssentials#372]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at RefactoringEssentials.CSharp.CodeRefactorings.IterateViaForeachAction.<>c__DisplayClass2_0.<Handle>b__0(CancellationToken ct)
   at RefactoringEssentials.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

![image](https://user-images.githubusercontent.com/383256/42171640-774aeb86-7e22-11e8-81e3-1957dc61f8d3.png)

**Comment by nick-morhun** [comment]
Any code example?
